version: 2.1

jobs:
  build:
    docker:
      - image: circleci/elixir:1.13-node
        environment:
          MIX_ENV: test
          MIX_TEST_DB_HOST: localhost

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: demo_test
          POSTGRES_PASSWORD: postgres

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix archive.install --force hex phx_new
      - run: mix do deps.get, compile
      - run: mix test
      - slack/notify:
          color: "#42e2f4"
          mentions: "U01HBU00DKM"
          message: This is a custom message notification
          webhook: https://hooks.slack.com/services/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
orbs:
  slack: circleci/slack@4.6.2
workflows:
  your-workflow:
    jobs:
      - build
